"""
Program Executor module for the RFT-ILP neuro-symbolic architecture.

This module uses a Prolog engine to execute a learned logic program on a new set
of facts to generate the output facts.
"""

from pyswip import Prolog
from typing import List

class ProgramExecutor:
    def __init__(self):
        self.prolog = Prolog()

    def execute_program(self, program: str, facts: List[str]) -> List[str]:
        """
        Executes a learned program on a set of facts.

        Args:
            program: The learned logic program.
            facts: The input facts for a single grid.

        Returns:
            A list of output facts generated by the program.
        """
        self.prolog.retractall("fact(_)")
        self.prolog.retractall("rule(_)")

        # Assert facts and program
        for fact in facts:
            self.prolog.assertz(f"fact({fact})")
        
        # pyswip doesn't directly support consulting from a string,
        # so we need to parse and assert each rule.
        rules = [r.strip() for r in program.split('.') if r.strip()]
        for rule in rules:
            self.prolog.assertz(f"rule({rule})")

        # Query for output objects
        output_facts = []
        # This is a simplified query. A real implementation would need to be more robust.
        try:
            for soln in self.prolog.query("output_object(Ex, Obj)"):
                output_facts.append(f"output_object({soln['Ex']}, {soln['Obj']}).")
        except Exception as e:
            print(f"Error querying Prolog: {e}")

        return output_facts
